### ISSUE TITLE
rook-operator cannot access to Ceph cluster after recreate the cluster.

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#1043]
## What

The credentials held by the rook-operator do not seem to be properly updated.
So recreating Ceph cluster causes access failure of rook-operator to ceph cluster.

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by kfyharukz** [comment]
This situation occurred due to the wrong procedure to delete the ceph-hdd CephCluster.

We should the following steps to delete a CephCluster:
1. Delete all resources using the target CephCluster (OBC, PVC with RBD, ObjectStore, CephBlockPool)
2. Delete the target CephCluster resource
3. Delete PVCs for OSDs
4. Clear devices for PVs (such as with dd or shred)
5. Delete PVs

ref: https://bozuman.cybozu.com/k/#/space/3801/thread/38010/2457406
