### ISSUE TITLE
Check the release note of Kubernetes 1.15

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#425]
## What

To conform to kubernetes 1.15, check the release note of this version.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md

## How

Read it and pick the necessary actions.
Necessary actions should be listed as comments for this issue.

e.g. https://app.zenhub.com/workspaces/neco-5ca28d055128c041a68c0a8f/issues/cybozu-go/neco/236

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by binoue** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#node
Enforcement of these restrictions should be done through admission control instead (e.g. PodSecurityPolicy).
なので、--allow-privileged=はなくなった

ckeではkubeletのParamに--allow-privileged=trueいれてるから、消さないといけない

**Comment by binoue** [comment]
DaemonSet, Deployment, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.

neco-appsのnetwork-policy_test.goでapiVersion: extensions/v1beta1が使われてる

**Comment by morimoto-cybozu** [comment]
> Hyperkube short aliases have been removed from source code, because hyperkube docker image currently creates these aliases.

This does not affect us, because our Dockerfile also creates these aliases.
https://github.com/cybozu/neco-containers/blob/master/hyperkube/Dockerfile

**Comment by binoue** [comment]
Use `apiextensions.k8.io/v1` instead of `apiextensions.k8.io/v1beta` in self-made CRD in topolvm repo.

**Comment by morimoto-cybozu** [comment]
Update all CRDs in neco-go/* repositories, and we'll see what happens.

**Comment by morimoto-cybozu** [comment]
> Continued deprecation of extensions/v1beta1, apps/v1beta1, and apps/v1beta2 APIs

[coil/mtest/pod.go](https://github.com/cybozu-go/coil/blob/master/mtest/pod.go) uses `apps/v1beta1`.
This can be fixed easily.

[cke/resource.go](https://github.com/cybozu-go/cke/blob/master/resource.go) refers to k8s.io/api/extensions/v1beta1.
I'm not sure how this works...

**Comment by morimoto-cybozu** [comment]
[cke/resource.go](https://github.com/cybozu-go/cke/blob/master/resource.go) uses the extensionsv1beta1 package to allow old-style policy manifests for [user-defined resources](https://github.com/cybozu-go/cke/blob/master/docs/user-resources.md).
PodSecurityPolicy and NetworkPolicy are now served from `policy/v1beta1` and  `networking.k8s.io/v1` respectively.
We can drop support for policies in `extensions/v1beta1` by stating it in the change log.

**Comment by morimoto-cybozu** [comment]
Problems marked as "not used", listed in "Urgent Upgrade Notes":

* `kubectl scale job`, deprecated since 1.10, has been removed.
* The deprecated `--pod`/`-p` flag for `kubectl` exec has been removed.
* The deprecated flag `--conntrack-max` has been removed from kube-proxy.
* The deprecated kube-proxy flag `--cleanup-iptables` has been removed.
* The deprecated kubelet security controls `AllowPrivileged`, `HostNetworkSources`, `HostPIDSources`, and `HostIPCSources` have been removed.
* The `Node.Status.Volumes.Attached.DevicePath` field is now unset for CSI volumes.
* (and vendor specific functionalities)

**Comment by morimoto-cybozu** [comment]
> kube-proxy no longer automatically cleans up network rules created by running kube-proxy in other modes.

In my understanding, changing the mode of kube-proxy is out of the scope of CKE.

**Comment by masa213f** [comment]
DaemonSet, Deployment, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.

neco-apps: monitoring/base/grafana/deployment.yaml の中で、extensions/v1beta1のDeploymentが使われている。
