### ISSUE TITLE
test in README is out-of-date (and not working?)

### ISSUE THREAD

**Issue by ggilley** [cybozu-go/neco#719]
The virtual data center test seems to be out-of-date. It's missing swtpm in the list of packages to install.

When I run the test, it fails. I'm experimenting with the system, so it's hard for me at the moment to know what's going wrong. Any pointers?

```
$ make test
./test.sh "" ""
preparing placemat...
preparing placemat...
preparing placemat...
Running Suite: Data Center test
===============================
Random Seed: 1578460704
Will run 30 of 30 specs

Preparing...
failed to dial: 10.72.48.0
failed to dial: 10.72.48.0
failed to dial: 10.72.48.0
failed to dial: 10.72.48.0
waiting for auto-config has completed
Failure [729.259 seconds]
[BeforeSuite] BeforeSuite 
/home/ggilley/neco/dctest/bootstrap/suite_test.go:21

  Timed out after 600.000s.
  Expected success, but got an error:
      <*ssh.ExitError | 0xc000546500>: {
          Waitmsg: {status: 1, signal: "", msg: "", lang: ""},
      }
      Process exited with status 1

  /home/ggilley/neco/dctest/before.go:44
------------------------------

Ran 30 of 0 Specs in 729.260 seconds
FAIL! -- 0 Passed | 30 Failed | 0 Pending | 0 Skipped
--- FAIL: TestDCtest (729.26s)
FAIL

Ginkgo ran 1 suite in 12m23.871254532s
Test Suite Failed
Makefile:107: recipe for target 'test' failed
make: *** [test] Error 1

```

As far as I can tell, placemat is working .

```
$ pmctl node list
boot-0
rack0-cs1
rack0-cs2
rack0-ss1
boot-1
rack1-cs1
rack1-cs2
boot-2
rack2-cs1
boot-3
rack3-cs1
```

**Comment by morimoto-cybozu** [comment]
@ggilley 
Thank you for testing.
As you have reported, the testing procedures in README do not seem to work correctly.
I'm sorry to leave README stale.

My team does not use the raw PC environment for testing.
Instead, we set up the testing environment on GCP by using `necogcp`, as described in [docs/gcp](../tree/master/docs/gcp).
The `necogcp` command installs many packages (cf. [gcp/arfitacts.go](../tree/master/gcp/artifacts.go)) and performs various setup operations (cf. [gcp/vmxenabled.go](../tree/master/gcp/vmxenabled.go)).
These extra operations are not reflected in README currently.
I will update README for testing, but it will take a while.

As for your situation, the test failed in confirming the completion of boot servers' initialization driven by cloud-init.
The log messages of cloud-init will contain the information for debugging.
The logs are output in `/var/log/cloud-init-output.log` on each boot server.
The log file can be accessed by executing `./dcssh boot-0` (and `boot-1`, `boot-2`) in `dctest` directory.

There is a possibility that some child process of `placemat` was killed by out-of-memory because `placemat` requires a huge amount of memory for dctest.
This cannot be examined by `pmctl node list` because it just shows the definitions of the cluster.
Please check the processes by `ps`.

**Comment by morimoto-cybozu** [comment]
@ggilley 
I've tested on Ubuntu 18.04 using GCP and updated README.
If you have trouble again, please make a new issue.
Thank you!
